-- Saya menggunakan AI untuk mengubah data json menjadi sql

Use leksikon;

INSERT INTO `sumber` (`id`, `nama_sumber`, `deskripsi`) VALUES
(1, 'Bausastra Indonesia-Jawi', 'Purwadarminta, c. 1939, #1979.'),
(2, 'Javanese-English Dictionary', 'Horne, 1974, #1968.'),
(3, 'Bausastra Jawa', 'Poerwadarminta, 1939, #75.'),
(4, 'Kawi Lexicon', 'Wojowasito, 1980, #575.'),
(5, 'Kawi - Indonesia', 'Wojowasito, 1977, #1019.'),
(6, 'Javaansche Woordenlijst', 'De Nooy, 1893, #24.'),
(7, 'Javaansch-Nederlandsch Handwoordenboek', 'Gericke en Roorda, 1901, #918.'),
(8, 'Javaansch-Nederduitsch Woordenboek', 'Gericke en Roorda, 1847, #16.'),
(9, 'Dictionnaire Javanais-Français', 'L\'Abbé P. Favre, 1870, #917.'),
(10, 'Têmbung Kawi Mawi Têgêsipun', 'Wintêr, 1928, #1506.'),
(11, 'Giri Sonta Course for Javanese (Lexicon)', 'Bakker, 1964, #286.'),
(12, 'Bausastra: Jarwa Kawi', 'Padmasusastra, 1903, #11.'),
(13, 'Kawi - Jarwa', 'Poerwadarminta, 1943, #1856.'),
(14, 'Babasan lan Saloka', 'Anonim, 1908, #1278.'),
(15, 'Jampi Susah', 'Tan Kun Swi, 1924, #1105.');

INSERT INTO `entri` (`term`, `definition`, `sumber_id`) VALUES
('abdi', 'abdi, batur.', 1),
('abid', 'wêkêl pangibadahe.', 1),
('adat', 'adat, padatan, kalumrahan, tatacara; ber''adat: 1 nindakake kalumrahan, miturut padatan; 2 sinewaka; di''adatkan: didadèkake padatan; ter''adat: wis têtêp dadi padatan.', 1),
('adat isti''adat', 'sakèhing tatacara lan padatan.', 1),
('adat lembaga', 'tatacara, padatan.', 1),
('adat pusaka', 'padatan naluri saka lêluhur.', 1),
('adil', 'adil, di''adili: diadili; peng''adilan: pangadilan.', 1),
('afiat', 'waras, bagas waras.', 1),
('afrit, ''ifrit', 'setan, dhêmit.', 1),
('afuah, afwah', 'kasêktèn kang marga kasucian.', 1),
('aib', 'cacad, kuciwa, kasalahan; di''aibkan: dicacad, diwirangake, dirèmèhake.', 1),
('ain', 'mata, undêraning prakara.', 1),
('ajab', 'gumun.', 1),
('ajaib', 'gumun, nggumunake, anèh.', 1),
('Ajam', 'Pèrsi.', 1),
('akad', 'prajanjian, layang pikukuh.', 1),
('akal', '1 nalar, reka; 2 (-budi) pikiran, budi kang bênêr; 3 akal, kajuligan; ber''akal: sugih akal, pintêr; masuk''akal: kêtêmu nalar; di''akali: diakali, diapusi.', 1),
('akas', 'kosokbalèn.', 1),
('akekah', 'slamêtan ngêthok rambut bayi.', 1),
('akibat', 'kawusanane, têmahane, kadadeyane.', 1),
('akik', 'akik.', 1),
('akil balig', 'wis diwasa.', 1),
('akrab', 'urang.', 1),
('ala', '''ala kadarnya: miturut sakuwasane.', 1),
('alaihissalam', 'kaslamêtan ana ing dhèwèke.', 1),
('alaikum assalam', 'kaslamêtan ana ing kowe.', 1),
('alam', 'I 1 alam, jagad saisine; 2 krajan gêdhe. II gêndera.', 1),
('alamat', 'I têtêngêr, tandha, ngalamat, sasmita; 2 adrês; 3 gêndera; di''alamatkan: dingalamati marang. II luhur, mulya, kuncara, sêmuwa.', 1),
('alim', 'wong pintêr babagan agama.', 1),
('am', 'I umum, sumarambah, kaprah. II taun.', 1),
('amal', 'panggawe bêcik; di''amalkan: ditindakake tmr. piwulang lsp.', 1),
('anbar', 'ambêr.', 1),
('aral', 'aral, alangan.', 1),
('arasy', 'dhamparing Pangeran.', 1),
('arif', 'sarjana, wong pintêr, wicaksana.', 1),
('asabat', 'urat, saraf.', 1),
('asar', 'wayah sêmbahyang asar.', 1),
('askar', 'wadyabala.', 1),
('asyik', 'kc. asik.', 1),
('asyura', 'tanggal sapuluh sasi Muharam (Sura).', 1),
('atar', 'ar. lênga wangi ut. ombèn-ombèn.', 1),
('aulia', 'uliya, wong suci.', 1),
('aurat', '1 wuda, 2 urat (wêwadi).', 1),
('azab', 'siksaning Pangeran.', 1),
('azan', 'adan.', 1),
('azimat', 'jimat.', 1),
('ibadah', 'pangibadah, agama.', 1),
('ibarat', '1 ngibarat, pêpindhan; 2 pindha, kaya; di''ibaratkan: dingibaratake, dipindhakake kaya.', 1),
('iddah', 'idah.', 1),
('idil fitri', 'lêbaran.', 1),
('iffrit', 'setan.', 1),
('ilat', 'alangan, aral.', 1),
('illah', 'alangan, aral.', 1),
('ilmu', 'ngèlmu, kawruh; ber''ilmu: putus ing kawruh, pintêr.', 1),
('inayat', 'pitulungan.', 1),
('isa, ''isya', 'wayah sêmbahyang ngisa.', 1),
('isyarat', 'tanda, sasmita, ngalamat.', 1),
('izzah', 'kamulyan, kaluhuran.', 1),
('ukab', 'manuk garudha.', 1),
('ulama', 'ngulama, ahli agama.', 1),
('umum', 'umum; diumumkan: digiyarake.', 1),
('umur', 'umur.', 1),
('aa', ': imperative suffix. Rene-a. Come here! Kowe ana-a ngomah bae. You stay home.', 2),
('ab', ': subjunctive suffix. 1 may [it happen]. Bisa-a enggal dadi. I hope it will be ready soon. 2 (in order) to; so that. Bêcike ditutupi bisa-a aja nganti dirubung lalêr. It should be covered so flies can''t get into it. 3 even though; (even) if. Sênajan mêngkono-a even so. Mangsa bisa-a. As if you could do it! Nakal-a kae wong iku anakku. He may be bad but he''s my son. Olèh-a dhuwit kêna dianggo tuku montor. If I had the money I''d buy a car. 4 with doubled adjective far more so. Gêdhe-gêdhe-a iki. This one is much bigger. 5 with doubled word [not] even. Aku ora entuk layang siji-siji-a. I didn''t get a single letter. 6 with doubled question word [what]ever. Sapa-sapa-a sing arêp mlêbu kudu wisuh dhisik. Anyone who wants to come in has to wash his hands first. Piye-piye-a kae kowe kudu lunga. No matter what, you have to go.', 2),
('ake', ': ng, -akên kr (-kake, -kakên after vowel) (causative suffix) 1 to [do] on smn''s behalf. Aku ditukokake buku. He bought me a book. 2 to have smn [do]; to have sth [done]. ndandakake pit to have a bicycle repaired. 3 to use [noun]. m-bêdhil-ake to shoot a gun. 4 to bring about [an act, a condition] ng-gampang-ake to make sth easy. m-bêcik-ake to improve sth. n-turu-kake to put smn to sleep. di-cara-Jawa-kake to be Javanized. 5 to [do] by accident. m-pêcah-ake gêlas to break a glass unintentionally. 6 (I guess) I''ll [do] (see also TAK-). Aku dak ng-golèk-ake tamba kowe mênyang dhoktêran. I''ll go to the hospital and get you some medicine. See also individual entries for applicable meanings.', 2),
('amu', ': formal var of -MU.', 2),
('an', ': (or -n or -nan after vowel) (suffix) 1 act or way of [do]ing. dina kanggo suntik-an the day we get our injections. Dus-an-e angèl. It''s hard to bathe him. jaran tunggang-an a riding horse. 2 place where [noun] is found or where [verb] is done. dhoktêr-an hospital. kaum-an section where devout Moslems live. Harjita-n Mr. Harjita''s house. lèrèn-an stopping/resting place. lungguh-an seat, place to sit. kê-kêmbang-an place where flowers grow or are placed. 3 that which is used for [do]ing. balèn (bali-n) a ride home/back. bukak-an blèg can opener. saring-an strainer. sêkolah-an a school. timbang-an scales (for weighing). tukon (tuku-n) purchase price; money for buying. 4 that which resembles [noun] but is smaller; an artificial or toy [noun]. jaran-an rocking horse. gunung-an hill. kodhok-an small frog. 5 many [doubled nouns]; various kinds of [reduplicated nouns]. godhong-godhong-an many leaves; foliage. gê-godhong-an all kinds of leaves, any kind of leaf. woh-woh-an fruits. 6 that which does, is characterized by, or undergoes [root]. apik(-apik)-an sth nice, esp. a surprise. Banyumas-an Banyumas-style speech. jêro-an intestines, insides. murah-an junk, cheap stuff. rewang-an helper. sabrang-an foreigner, outsider. sak angkat-an one load. dhun-dhun-an things that have been unloaded. 7 performance, ceremony, etc. in which [noun] is centrally involved. manton (mantu-n) wedding ceremony. wayang-an shadow-play performance. 8 nth (fraction formative). sapratêlon (sa-pra-têlu-n) 1/3. 9 having been [done]. gawe-an Sala made in Solo. layang amplop-an a letter (which had been put) in an envelope. 10 to [do, as a group] in a leisurely way with enjoyment. gêguyon (gê-guyu-n) to laugh and joke. langèn (langi-n) to go swimming. lungguh(-lungguh)-an to sit around talking and relaxing. 11 prone to [root]. wêdèn (wêdi-n) timid. bisa-n competent, handy. bungah-an happy-go-lucky. matèn (mati-n) hard to keep alive. ng-kandêl-an trusting, gullible. bosên-an easily bored. 12 to put on or wear [root]. sêpaton (sêpatu-n) to put/have on shoes. gêlung-an to do one''s hair in a bun. 13 to imitate/simulate [root]. jaran-an to trot like a horse. pincang-an to limp like a cripple. sinau-sinau-an to try to look as if one is studying. 14 to take turn [do]ing, [do] one after the other. Tilpune mung siji, dadi mung gêntèn-an. There''s only one phone so we share it. Ing kutha kene uripe lampu listrik gilir-an. In this city, the residence blocks take turns having the light on. Pulpèn apik ngono kok mung kanggo cêpak-an silih-silih-an. How come you keep such a nice fountain pen just lending people? Pamplèt-pamplèt kuwi pancèn mligi sêdhiyan jupuk-jupuk-an para tamu. Those pamphlets are for the audience to help themselves to. 15 approximately n. limang jam-an about 5 hours. jam lima-nan about 5 o''clock. Omahe nomêr têlu-nan. His house number is 3 or sth like that. ngaso sêminggu-an to take about a week off. taun sèkêt-an nêm or taun sèkêt nêm-an around [19]56. 16 an unspecified number of n''s. Lungane sêsasèn (sê-sasi-n). He was gone for months. Ewon (èwu-n) sing padha mati. Thousands died. 17 generalized state of [adjective]. manis jangan sing wutuh-an a stick of whole cinnamon. Lêgèn mau didol mêntah-an bae. He sold the sugar-palm sap unprocessed. 18 var of suffix -I when prefixed with KA-. See also KA...AN, PA...AN under PA- b ; also definition of doubled forms (Introduction, 3.1.1); also Introduction, 3.1.6.2. See also individual entries for applicable meanings.', 2),
('anab', ': (-nana after vowel) (suffix) 1 imperative form of suffix -I. Ng-rewang-ana bapakmu. Help your father! Wong ngêmis kae wènèh-ana sêga. Give that beggar some rice. Anakmu ombè-nana jamu iki. Have your child take this medicine. 2 subjunctive form of suffix -I: see -A b for subjunctive meanings. di-tamba-nana dikaya-ngapa no matter how much medicine you give him. Wong ala di-bêcik-ana iya bakal malês ala. Treat a bad person kindly and he''ll repay you with evil. Kowe manèh dak-wènèh-ana, sing anakku dhewe ora dak wènèhi. As if I''d give you any - I didn''t even give any to my own child! Dhoktêre atur-ana mrene supaya wong lara iki di-priksa-nana. Send for the doctor so he can examine this sick man. Sanajan tak wènèh-ana satus rupiah mêksa durung cukup! I gave him 100 rupiahs and it still wasn''e enough!', 2),
('aneb', ': ng, -anipun kr (-nane, -nanipun after vowel) optative form of suffix -I. Anggone. nggawa wangune rêkasa, dak rewang-ane. What he''s carrying looks heavy; I''ll help him. Kucingmu lara, dak pati-nana bae. Your cat is sick-let me put him out of his misery. See also TAK-.', 2),
('anipun', ': optative suffix: kr for -ANE.', 2),
('antab', ': (-nta after vowel) ltry your. raka-nta your older brother.', 2),
('ec', ': ng, -ipun kr (-ne, -nipun after vowel and with certain kinship terms) 1 3d-person possessive suffix. potlod-e his/her pencil. buku-ne smn''s book. bapak-(n)-e smn''s father. êmbah-(n)-e smn''s grandparent. êmbok-(n)-e smn''s mother. ibu-ne, ibu''e smn''s mother. kakang-(n)-e smn''s older brother. Anak-e papat. They have four children. Sêpur mau laku-ne rikat bangêt. The train goes very fast. Bangêt kagèt-e. He was very much taken aback. Aku arêp ngrêksa omah-e Jogja. I''ll be looking after his Jogja house. wong sing jênêng-e Ali a man named Ali. Mêsthi kobong-e. Naturally it will burn (i.e. its burning is certain). Ana kanca-ne dolanan. A friend of hers came to see her. 2 your (oblique, respectful). Ngêndika-nipun basa Jawi kok sampun luwês sangêt. You speak Javanese very fluently. 3 of. panas-e gêni the heat of the fire. pit-e kakangku my brother''s bicycle. Dhuwit-e A kurang. A is short of money. 4 the aforementioned. Lodhong-e dipêcah. He smashed the jar. Dhèke ngulat-ulatake dodolan-e kabèh. He looked over all the merchandise. nalika dhèke têka rene ping pindho-ne the second time he came here. 5 the/smn''s action of [do]ing. Mangan-e alon-alon. He ate slowly. Mangan orane gumantung marang matêng-e sêga. Whether we eat or not depends on whether the rice is done. Kuwi kudu-ne ora kaya ngono. You shouldn''t do things like that. 6 the/smn''s ... ness. Sêpira dhuwur-e? How tall is he/it? Bungah-e ora karuwan. He was overjoyed. Olèhmu ngêntèni pirang jam suwe-ne? How long did you wait? 7 the/smn''s X is ... Lumrah-e usually (i.e. the usual thing is ...). Tuju-ne ora apa-apa. Luckily it was nothing serious. Sajak-e arêp udan. It looks like rain. Cêkak-e wong mono kudu tulung-tinulung. In short, people must help each other. Batin-e karêp-e apa. He wondered what she wanted. Wangsulan-e sing dodol ... The seller replied ... 8 in connection with [sth mentioned earlier]. Olèhe mangan ora ana swara-ne. They ate soundlessly (''their eating, there was no sound connected with it''). Yèn ana anake sing lara, prasasat ora ana ngaso-ne. When one of the children is sick, there''s no rest for her. Ing alas kono ana macan-e. That forest has tigers in it. Aku njaluk pangapura-ne. I beg your pardon for it. Têlung dina-ne dhèke mati. Three days later (i.e. after it) he died. Nanging ana nanging-e manèh. But there''s another "but". 9 another X; the other X (of a pair or series). Sing siji biru, siji-ne abang. One is blue, the other is red. Sing siji wuta, sing siji budhêg, sing siji-ne bisu. One was blind, another was deaf, the third was mute. Sing lima maca, papat-e manèh nulis. Five of them read, the other four wrote. 10 per, each, a(n). Sêdina-ne kowe olèh pira? How much do you earn per day? Nêgara mau mbutuhake daging rong yuta kilogram sêtaun-e. This nation consumes 2 million kilograms of meat a year. 11 [time] after [time]; each [time] in the continuing series. Sing mènèhi panganmu sabên dina-ne sapa? Who gives you your food day in and day out? Tanggal limalas sabên sasi-ne, sêgara mau angok-angok mêngidul antarane jam rolas awan nganti jam loro. The 15th of every single month, the tide is out (southward) between 12 noon and 2 P.M. 12 by contrast. mau-ne as contrasted with formerly. Wong saomah padha bungah, mau-ne nangis wae. The wole family rejoiced; before, there had been nothing but weeping. Durung pulih kaya mau-ne. He was not yet restored to (his previous condition of) health. Aku saiki-ne lagi nyèlèngi. Now, on the other hand, I''m saving my money. 13 of course! by all means! (between two occurences of the same verb or adjective). Bisa-ne bisa, ning kêsèd kok. Of course he can do it - he''s just lazy. Apa banjur kêna diênggo nyèlèngi? - Kêna-ne kêna. Can it be used as a piggy bank? - By all means. Apa cukup diênggo tuku sêpedha anyar? - Cukup-e cukup, nanging aku gêmi. Is there enough to buy a new bicycle? - Oh yes, plenty; but I''m frugal. 14 second element of psv optative circumfix: see TAK- 3 and Introduction, 3.1.5.4 chart.', 2),
('êm', ': inf var of -UM-.', 2),
('ên', ': (-nên after vowel) 1 (ng) psv imperative suffix. Dêlêng-ên. Look (at it)! Pring kae gawa-nên mrene. Bring that bamboo over here. 2 suffix for a bodily process or condition. Drijine gêtih-ên. His finger bled. Matane walang-ên. His eyes bugged out. aras-aras-ên nyambut gawe lackadaisical toward one''s work. mata dhuwit-ên money-mad. 3 second element of KA ... ÊN circumfix. k-adhêm-ên too cold.', 2),
('i', ': (-ni after vowel) (suffix) 1 to [do] repeatedly, regularly; to [do] many times or to many objects. ng-undhuh-i pêlêm to pick mangoes. m-pênthung-i asu to beat a dog. 2 to [do] to [sth, as direct object]. n-tampa-ni tamu to receive a guest. n-duwe-ni sawah to own a rice paddy. 3 to direct or apply [root] to sth. ng-lungguh-i kursi to sit on a chair. n-tulis-i buku to write in a book. ng-kirim-i layang bapakne to send a letter to one''s father. ng-ênggon-i omah to live in a house. ngê-doh-i piala to stay away from evil. m-basa-ni wong cilik to speak Krama to the common people. ng-kusir-i andhong to drive a horse cab. n-têgês-i têmbung to give the meaning of a word. Aja n-dhisik-i kancane. Don''t get ahead of the others. di-loro-ni to be set upon by two attackers. 4 to provide sth with [root]. m-pagêr-i to enclose with a fence. ng-ombe-ni wong to give smn a drink. m-bumbu-ni jangan to season soup. ny-slamêt-i to hold a ritual feast in honor of. 5 (acv only) having the characteristics of [root]; to [do] characteristically. m-wedok-i womanly. n-dhêdhêt-i to tighten, become taut. m-brodhol-i to shed, molt. 6 (with TAK- prefix) I guess I''ll ... Tak ng-rewang-i ibu. I''ll go help Mother. See also -AN 18; see also individual entries for applicable meanings.', 2),
('in', ': ltry: psv infix 1 formal var of DI-. t-in-imbang compared [with]; than. basa r-in-êngga elegant (fancy) language. k-in-ubêng ing pagêr kawat surrounded by a wire fence. g-in-awe-gawe false, assumed [of a misleading mannerism or aspect]. 2 (in second member of doubled root) to [do] successively or reciprocally. tulung-t-in-ulung to help each other. pati-n-p-in-ati-nan (patèn-pinatènan) to kill each other. Mêngkono satêruse nganti turun ping pitu, walês-w-in-alès. And so in this way one avenged the next for seven generations.', 2),
('ingc', ': (-ning after vowel) of. katrêsna-ning biyung a mother''s love. kêdhèp-ing mripat the wink of an eye. lara-ning anake wedok his daughter''s illness. pucuk-ing buntut the tip of its tail. swara-ning tangise the sound of her weeping. molah-malih-ing kahanan changing conditions. ing satêngah-ing sêgara at sea; in the middle of the ocean. ana sangisor-ing wit underneath the tree. ing sawiji-ning dina on a certain day.', 2),
('ipun', ': (-nipun after vowel) suffix: kr for -E c .', 2),
('ipun', '(ipUn) : k. -e.', 3),
('ira', '(­irO) : kw 1 -e, -ne; 2 -mu; kc. sira.', 3),
('irab', ': (-nira after vowel) oj the; his, her (ltry var of -E c ).', 2),
('ireka', '(­irekO) : kw -e, -ne.', 3),
('ireka', ': -irèki, -irèku, (-nireka etc. after vowel) oj the; his, her (ltry var of -E c ).', 2),
('irèki', '(irEki) : prik. -ireka.', 3),
('irèku', '(irEku) : prik. -ireka.', 3),
('kake', ': ng, -kakên kr post-vowel form of sufix -AKE.', 2),
('kakên', ': kr for -KAKE.', 2),
('keb', ': (-kke after vowel) inf var of -AKE (suffix).', 2),
('kke', ': inf post-vowel var of -AKE.', 2),
('kna', ': post-vowel form of causative imperative/subjunctive suffix -NA.', 2),
('knê', ': post-vowel form of causative optative suffix -NE.', 2),
('ku', ': ng, kula kr my, our. Omahku adoh. My (our) house is far away. Olèhku nyambut gawe tumêmên. I worked really hard. Iki dhuwitku dhewe. This is my own money.', 2),
('l', ': infix inserted after initial consonant of certain words, denoting repeated, continuing, and/or multiple actions or effects. See individual listings.', 2),
('n', ': post-vowel form of suffix -AN.', 2),
('nab', ': (-kna after vowel) imperative and subjunctive form of suffix -AKE: see chart, Introduction 3.1.5.4). N-jupuk-na sêga adhimu. Get your brother''s rice for him. Aku jupuk-na dluwang. Get me some paper. Saridin kae dak kandha-kna wong tuwane, mêsthi disrêngêni. Saridin would have been scolded if I had told his parents. See -A 2, 3, 4 for imperative meanings.', 2),
('nane', ': suffix post-vowel form of -ANE.', 2),
('nanipun', ': kr suffix post-vowel form of -ANIPUN: see -ANE.', 2),
('ne', ': ng, -nipun kr (suffix) 1 (-kne, -knipun after vowel) causative optative suffix: see chart, Introduction, 3.1.5.4. 2 post-vowel form of suffix -E c .', 2),
('nên', ': suffix post-vowel form of -ÊN.', 2),
('ni', ': suffix post-vowel form of -I.', 2),
-- Data dari JSON Kedua (adhiṣṭhita -> adilaga)
('adhiṣṭhita', ': (S) to be put, be placed.', 4),
('adhiwijña', ': S. sangat pandai; sangat berpengalaman.', 5),
('adhiwijña', ': (S) very clever; very experienced.', 4),
('adhiwinnā', ': S. seseorang isteri yang terdesak ke belakang kedudukannya, karena suaminya kawin lagi.', 5),
('adhiwinnā', ': (S) awife degraded in position because of the second wife.', 4),
('adhiwira', ': S. pahlawan yang besar.', 5),
('adhiwīra', ': (S) great hero.', 4),
('adho', '(aDo) : ngadho: nata Tg.', 6),
('adho', '(aDo) : I êngg.kn patrap, cara; di-[x] êngg: 1 ditrapake; 2 ditata, dipranata. II pc. adhuh.', 3),
('adho', ': zie adhuh .', 7),
('adho', ': var of ADHUH.', 2),
('adho', '(aDo) : zie dho.', 8),
('adhomuka', ': S. dengan muka tunduk.', 5),
('adhomuka', ': (S) with the face hanging down toward the breast.', 4),
('adhong', '(aDOG) : êngg. kn bngs. irig dianggo golèk iwak.', 3),
('adhong', ': KN. een mand of zeef van bamboe, die onder een der van de rijstvelden in een daarneven stroomende vliet vallende waterstralen gelegd wordt, om de vischjes op te vangen, zie bij wijah , Wk. vgl. cadhong .', 7),
('adhos', '(aDOs) : K.N. dun, mager; ,vermagerd [zie dhos].', 8),
('adhos', ': N.K. fluet, maigre.', 9),
('adhu', '(aDu) : di-[x] êngg. pc digadhon.', 3),
('adhu', ': zie adhuh .', 7),
('adhu', ': rg var of gadhu. ng/di-[x] to sue, bring legal action against. pa-ng-[x]-an lawsuit.', 2),
('adhu', '(aDu) : babo.', 10),
('adhuh', '(aDUh) : pc pasambat lara, gumun lsp.', 3),
('adhuh', ': of dhuh , (ook wel adho , of dho , en adhu , R.) KN. ach! helaas! Ar. S. 7, 4; ook wel een uitdrukking van teederheid en liefdesmart. Rh. wil de uitroep adhuh , bij een geval van pijn teruggeven met: auw! adhuh , ook zva. athuh , zie thuh . Ook zva. hèh , vóór een vocat BS. — ngadhuh , ach en wee roepen, weeklagen BG. 376. — pangadhuh , weeklacht. — karêdhuh , freq.? Wk.', 7),
('adhuh', '(aDUh) : K.N. zucht, weeklagt, uitdrukking van droefheid; ach! helaas! [Sd. Ml. id.]. Ook dhuh, ach! helaas! -ngadhuh, jammeren, kermen, weeklagen. -pangadhuh, gejammer, gekerm.', 8),
('adhuh', ': excl of pain, sorrow, joy. [x], lara wêtêngku. Ooo, my stomach hurts! [x] adhême. My but it''s cold! [x]lêga rasane atiku. What a relief! ng-[x] to exclaim in pain etc. Ora di-kapak-kapak-ake ng-[x]-[x]. Nobody did anything to him but he kept yelling ouch! [x] biyung (or [x] mbok) excl of pain. [x] biyung, wêtêngku lara. Oo, I have a stomach ache. [x] lae my goodnes! oh dear! why ... !', 2),
('adhuh', '(aDUh) : ah, alas; ngadhuh: to lament.', 11),
('adhuh', '(aDUh) : adhuh.', 10),
('adhuh', ': et dhuh , N.K. soupir, sanglot, exclamation de douleur; hélas. ngadhuh , lamenter, gémir, se plaindre. pangadhuh , lamentation.', 9),
('adhuk', '(aDU?) : di-[x] êngg. kn dipaculi didhudhukake; kc. campur adhuk.', 3),
('adhuk', ': [x]-an 1 [of soil] loosened for planting. 2 stirred from the bottom. m-[x] [of soil] dry and dusty. ng/di-[x] to bring what is underneath to the surface. Sawah anggone ng-[x] nganggo luku. Soil in a paddy is turned over with a plow. Jangane aja di-[x]. Don''t stir up the solids in the soup. Kopêre di-[x]-[x] pêgawe dhuane. The customs official plowed through my suitcase. pa-ng-[x] act/way of bringing things to the surface from underneath.', 2),
('adhuk', ': KN. madhuk , los en kruimelig van den grond, wanneer hij met de pacul , ploeg enz. goed door elkander gewerkt is, vgl. baludhuk , en marug , ''t tegenovergestelde van padhêt , Wk. — ngadhuk , den grond als boven los en kruimelig maken; goed door elkaar mengen, bv. zand met kalk en water. ° liwêt , rijst omroeren als zij half gaar en het water afgegoten is, opdat zij niet klontere, vgl. karu , kêdhuk , udhêg , tajin , êndhog , Wk.; mesten, bemesten G. — ngadhuki , mrv. kadhukan , los en dooreen gewerkt van den grond Wk. — ngadhukake , iets ergens onder mengen (ook door elkander werken of halen voor Wk.); vgl. carub , wor .', 7),
('adhul', '(aDUl) : di-[x]-[x] kn diudhal-udhal sarta diawut-awut.', 3),
('adhul', ': m-[x]-m-[x] or m-odhal-m-[x] 1 unkempt, disheveled; scattered about untidily. 2 to spend [money] foolishly. ng/di-[x]-[x] or ng/di-odhal-[x] 1 to mess things up, scatter things about. 2 to unravel a mystery, disclose a secret.', 2),
('adhul', ': ngadhul-adhul , 1. zva. ngèwèr-èwèr , zie èwèr , 2.; Tj. I, 745. — 2. zva. ambrodhol , (bij W. udhul ) uithangen van de darmen, intr. Tj. III, 344. — madhul-madhul , naar alle kanten opvliegen v. vederen, boomwol en derg., vgl. abul , Wk. — ngadhul-adhul , iets op een ruwe wijze door of uit elkander halen, dat de inhoud rondfladdert, zva. ngodhal-adhil , bv. usus.', 7),
('adhum', '(aDUm) : I kn. ak edhum, eyub. II [x]-[x]-an kn.ak: rêrêmbugan prakara wadi.', 3),
('adhum', ': var of ÊDUM. [x]-[x]-an to discuss (esp. private matters).', 2),
('adhum-adhum', ': zie adum-adum .', 7),
('adhwā', ': S. adhwan hilang.', 5),
('adhwā', ': (Sadhwan) gone, desappeared.', 4),
('adhwaryyu', ': S. pendeta yang sedang melakukan pekerjaan/tugas.', 5),
('adhwaryyu', ': (S) a priest who is carrying out his task.', 4),
('adhya', ': S. bersiap-siap; → adi .', 5),
('adhya', ': (S) to make preparations; to prepare oneself; see adi .', 4),
('adhyakṣa', ': S. saksi; kadi; hakim pertama; pengawas; kadhyakṣa berkedudukan sebagai hakim pertama.', 5),
('adhyakṣa', ': (S) witness; judge; first judge; supervisor kādhyakṣa to have the function of the first judge.', 4),
('adhyāpaka', ': S. guru.', 5),
('adhyāpaka', ': (S) teacher.', 4),
('adhyātmaka', ': S. ilmu kebatinan tertinggi.', 5),
('adhyātmaka', ': (S) highest knowledge about the soul.', 4),
('adhyātmakasukha', ': S. kebahagiaan batin tertinggi.', 5),
('adhyātmakasukha', ': (S) highest inner happiness.', 4),
('adhyāya', ': S. bab; bagian; pelajaran; murid; mangadhyāya mempelajari; membaca; pangadhyāyan usaha belajar.', 5),
('adhyāya', ': (S) paragraph; section; lesson; pupil; mangadhyāya to learn, to study, to read; pangadhyāyan attempt to study.', 4),
('adi', ': 1 fine, beautiful. 2 name of the 1st windu. [x]-n to serve, wait on, make things pleasant for. [x]-n-[x]-n 1 spoiled, overindulged. 2 that which is fine, beautiful, highly prized. ng-[x] to beautify, make fine. ng-[x] busana to dress beautifully. ng-[x] sarira to beautify one''s appearance. ng-[x]-[x] 1 overindulged, spoiled, demanding. 2 (psv di-[x]) to make beautiful; to value highly. ng/di-[x]-kake 1 to revere. 2 to have [clothing] made to order. ngadèkake klambi to have a dress made. ng/di-[x]-n-ni to make sth beautiful/fine. [x]aèng valuable and rare. [x] endah beautiful, splendid. [x]luhung of outstanding quality, highly esteemed [x]-luhunge laki-rabi the sacred nature of marriage. [x]-luhunging jogèd the exquisiteness of the dance. wulang [x]-luhung revered teachings. [x]-luwih fine, sublime, exalted. kagunan sing [x]-luwih the fine arts.', 2),
('adi', '(adi) : ade, adya, rasmi of rêsmi, di, luhung, linuhung, pèni, dhani, mulya, mapèni, maya; [adi-adi]: pèni-pèni, manggala; [ngadi-adi]: endaha, mèni; [ngadèkake]: mangendahkên; [kang adi-adi]: ngadi.', 12),
('adi', '(adi) : nice.', 11),
('adi', ': adya akan dihiasi; angadyani menerima baik; memilih; pangadyan penerimaan; persetujuan; adyan-adyan penerimaan. persetujuan.', 5),
('ādi', ': S. permulaan; pertama-tama; terutama; nomor satu; mangādi mulai dengan; makādi terutama; pangādi ketua; penghulu; pinakādi dijadikan pemimpin.', 5),
('adi', ': N.K. adya , Kw. excellent, éminent. adi-adi , très-excellent, très-éminent; être arrogant, orgueilleux. adinagara , titre, dignité d''un haut rang.', 9),
('adi', '(adi) : Kw. en K.N., ook adya, Kw. voortreffelijk, uitmuntend [= luwih, en bêcik, of luwih bêcik. Sd. ade, goed, hupsch; waard, dierbaar; Skr. âdi, uitmuntend, de of het eerste. Vrg. ook nadi]; ook naam van de tweede der vier Windu''s. -adi-adi, zeer uitmuntend; zich veel laten voorstaan, trotsch, hoogmoedig zijn [= luwih-luwih]. -adiwarna, een schoone gedaante [= rupa kang luwih bêcik]. adiningrat, de eerste der aarde, bijnaam van Surakarta en Jokyokarta. En zoo is dit woord, ook bij verkorting di, menigvuldig in gebruik in zamengestelde eigennamen, als Adinagara, Padmadipraja, enz.', 8),
('adi', '(adi) : langkung, ayu, bagus.', 10),
('adi', '(adi) : bêcik, linuwih.', 13),
('ādi', ': (S) begining; first; especially; first class; best; most exellent; mangādi to begin with; makādi especially; pangādi president, head; religious teacher; pinakādi to be appointed leader.', 4),
('adi', ': adyana will be decorated/illustrated; angadyani to accept, to welcome; to choose; pangadyan receipt, reception; agreement; adyan-adyan receipt, reception; agreement.', 4),
('adi', ': sae sarta aèng.', 14),
('adi', '(adi) : kw 1 linuwih; 2 bêcik; 3 kn. ar. windu; [x]-[x], adèn-adèn: (barang-barang) kang bêcik ut. pangaji bangêt; di-[x]-[x], diadèn-adèni kn. ak: 1 diaji-aji bangêt; 2 diêmi-êmi, digêmatèni bangêt; 3 êngg. pc. diugung, diênung-ênung (tmr. bocah cilik); di (-adèk)-adèkake; kc. èdi, ngadi.', 3),
('adi', ': I. (in samenst. soms verkort di , Wk. bv. digung = adigung ) KW. KN. ook wel èdi , (ook adya , KW.) uitmuntend, buitengemeen; fraai; schoon JZ. II; zva. luwih , en bêcik , (Skr. âdi , uitmuntend, de of het eerste, en adhi , opper- in samenstellingen); ook naam van de tweede Windu . adiningrat , de eerste, of het schoonste der aarde, betiteling van de vorstelijke residenties te Surakarta en Yogyakarta. adiraja , zva. pangapura gêdhe , Wk.(?) guna , (ook diguna , Wk.) trotsch op zijn bekwaamheid (Skr. adhiguṇa , voortreffelijk). gung , trotsch op zijn grootheid, hoogmoed. ° gang , trots op zijn lichaamskracht of gezondheid ZG. XIV, 263; JZ. II. ° kara , KW. zva. wisesa , JZ. II. linangkung , RL. 34b: adhikara , (Skr. adhikâra , oppergezag). rêtnadikara , KN. benaming van een bijzonder fatsoen van zadelblad WP. anglanadikara ? Waj. II, 122. adiwarna , (ontbr. W.) schoone gedaante of gelaat Wk. — ngadiwarna , ngadiawarna , zich opsieren Waj. I, 29, 440. ngadirupa , id. L. 48. ° laga , KW. BTDj. 530; Tj. N. P. 95 zva. paprangan , gevecht, en slagveld (niet bij W.). sêmbada ing °, DW. 147? adiyati , of ngadiyati , oudste Wijze (uit adi , en yati , zie ald.) hiernaar wordt genoemd een tijdvak van de oude mythische geschiedenis van Java JZ. II, 257, zie pralambang , Wk.) AS. adipati , (Skr. adhipati ) dipati , dipatya , KW. zva. ratu , Wk. pra dipati , of pra dipatya , KW. de adellijken, de adel; wordt verkl. door para tumênggung , (en door para ratu , ° panggêdhe , Wk.) KN. opperregent, opperlandvoogd. radèn adipati , (ook radèn dipati , dèn dipati , Wk.) titel van den Rijksbestierder (Grootvizier) te Surakarta en Yogyakarta. Verder titel van alle regenten op Java en Madura (de Vorstenlanden uitgezonderd) die niet Radèn Tuměnggung heeten, of den Pangeran s-titel voeren. het praedicaat Adipati komt voorts toe aan de opperhoofden der vrouwen in de kraton s van Solo en Yogya R. en T. pangeran adipati , een meer vorstelijke titel, die aan Prinsen van hoog aanzien verleend, en (verbonden met arya ) ook gevoerd wordt door de regeerende Prinsen Mangku-nagårå en Pakualam. Pangeran adipati anom , titel van den Kroonprins in de Vorstenlanden. — adi-adi , zva. luwih-luwih , en zich veel laten voorstaan; trotsch, hoogmoedig G. busana adi-adi , BTDj. 103. kang adi-adi , fraaiigheden, kostbaarheden Wk. — ngadi-adi , KN. ngados-ados , KD. AS. veeleischend K. 12, 8, 11; veel noten op zijn zang hebben Wk. Ook zva. angrêngga , versieren JZ. II. — adèn-adèn , voortreffelijke personen als paṇdhita ''s of geleerden; ook wat als een zeldzaamheid, bijzonder fraai of kunstig gemaakt is, kunstwerk Wk. — ngadèkake , (vlg. Wk. ook ngèdèkake ) zva. ngunggulake , BS. Wk. Een ander zie bij de , I. — kadipatèn , N. (vlg. Wk. KN.) kadospatèn , K. het hof of het gebied van een Pangeran-adipati , inzonderheid van den Kroonprins (zijne waardigheid BTDj. 328). bupati kadipatèn anom , te Solo een der bupati anon-anon , chef v. h. huis van den kroonprins R. en T. kadi , en ° ing kene , van hier af te beginnen. — makadi , KW. tot eerste, tot voorganger hebbende KO. 29. II. zva. abdi , Gr. L.', 7),
('adi', '(adi) : -ngadi-adi, N., ngados-ados, K., en ngadèkake, N., -kên, K., z.ben.', 8),
('adi', '(adi) : linuwih, bêcik.', 15),
('adi-adi', '(adi­adi) : zie adi.', 8),
('adi-aèng', '(adi­aEG) : dutedya.', 12),
('adib', 'ngrêti tatakrama.', 1),
('adibusana', '(adibusOnO) : ng-[x]: macak, dandan.', 13),
('adibusana', '(adibusOnO) : kw sandhangan kang bêcik; ng-[x] kw: macak, dandan.', 3),
('ādidewa', ': S. dewa yang tertinggi; pinakādidewa dianggap jadi dewa yang tertinggi.', 5),
('ādidewa', ': (S) the highest god; pinakādidewa regarded as the highest god.', 4),
('ādidewatā', ': S. yang terpenting di antara dewa-dewa.', 5),
('ādidewatā', ': (S) the highest amongst the gods.', 4),
('adigang', ': (to make) an arrogant display of one''s superior power.', 2),
('adigang', '(adigaG) : ambêg unggul, ngêndêlake kuwasane.', 13),
('adigang', '(adigaG) : kn. ak ngêndêl-êndêlake ênggone rosa (kuwat, digdaya, kuwasa).', 3),
('adiguna', ': (to make) an arrogant display of one''s superior knowledge.', 2),
('adiguna', '(adigunO) : ambêg unggul, ngêndêlake kadigdayane.', 13),
('adiguna', '(adigunO) : kn. ak. ngêndêl-êndêlake kapintêrake (kaluwihane).', 3),
('adigung', ': (to make) an arrogant display of one''s superior status. Dhèke isih ênom, mulane banjur adigang [x] adiguna. He''s young so he tries to impress people.', 2),
('adigung', '(adigUG) : ambêg unggul, ngêndêlake kaluhurane.', 13),
('adigung', '(adigUG) : kn. ak ngêndêl-êndêlake kaluhurane.', 3),
('adik', 'adhi; adik beradik: sadulur kakang adhi.', 1),
('adikara', ': zie bij adi .', 7),
('adikara', '(adikOrO) : wisesa, linangkung.', 10),
('adikara', 'adi endah garapane (wujude lsp.).', 1),
('adil', ': just, impartial, equitable. anggêr-anggêr sing [x] fair regulations. [x]-ing hyang divine justice. ke-[x]-an justice. kêadilan sosial social justice. ng/di-[x]-i 1 to judge; to act as judge. 2 to put smn on trial. pa-ng-[x]-an law court. pa-ng-[x]-an adat court of customary (rather than codified) law. [x] makmur characterixed by justice and prosperity.', 2),
('adil', ': ook wel ngadil , KN. rechtvaardig, rechtvaardigheid; recht Ar. [Arab] v. d. B. vrg. ukum ). adil kukum , BTDj. 260? vgl. AS. 260. ratu adil , de rechtvaardige vorst, die vlg. de meening van vele Javanen met het einde der wereld of van deze wereldperiode zal optreden Zg. XXXII, bl. 123. — ngadili , berechten. kaadilan , pass. en rechtvaardigheid. — pangadilan , rechtspraak R., rechterlijke uitspraak G.; gerecht, gericht; rechtbank.', 7),
('adil', '(adIl) : niti, sidya-sidana; [ngadili]: manidyasani, ngrajaniti; [luwih adil]: ambahudhêndha; [panggêdhening pangadilan]: prawara, mahasidyana.', 12),
('adil', ': et ngadil , N.K. droit, justice: juste. ngadili , faire droit, parler juste. pangadilan , la justice, le droit, tribunal. adilan , justice, droit.', 9),
('adil', '(adIl) : of ook ngadil, K.N. het regt, geregtigheid; regtvaardig [Ar. ''aadil; Sd. Ml. id.]. -ngadili, regt doen, regt spreken. -pangadilan, regterlijke uitspraak; geregt, gerigt; regtbank; het regt.', 8),
('adil', '(adIl) : (A) kn jêjêg anggone nibakake pêpancasan, ora pilih sih; di-[x]-i: dipriksa (ditimbang-timbang) êndi kang ala (salah) êndi kang bêcik (bênêr); kc.pangadilan.', 3),
('adilaga', ': oj war, battle.', 2),
('adilaga', ': Kw. champ de bataille.', 9);

-- Contoh untuk 'abdi' (Entri ID 1)
INSERT INTO `contoh_penggunaan` (`entri_id`, `contoh_teks`, `terjemahan`) VALUES
(1, 'Dadi abdi dalem kudu sing sabar.', 'Jadi abdi (pelayan) keraton harus yang sabar.');

-- Contoh untuk 'adat' (Entri ID 3)
INSERT INTO `contoh_penggunaan` (`entri_id`, `contoh_teks`, `terjemahan`) VALUES
(3, 'Adat desa kudu diugemi.', 'Adat desa harus dipegang teguh.');

-- Contoh untuk 'adil' (Entri ID 7)
INSERT INTO `contoh_penggunaan` (`entri_id`, `contoh_teks`, `terjemahan`) VALUES
(7, 'Hakim kudu mutusake perkara kanthi adil.', 'Hakim harus memutuskan perkara dengan adil.');

-- Contoh untuk 'akal' (Entri ID 17)
INSERT INTO `contoh_penggunaan` (`entri_id`, `contoh_teks`, `terjemahan`) VALUES
(17, 'Akal budi iku sing mbedakake menungsa karo kewan.', 'Akal budi itu yang membedakan manusia dengan hewan.');

-- Contoh untuk 'adhuh' (Misal, Entri ID 123 setelah digabung)
-- Ganti 123 dengan ID yang benar setelah insert semua entri
INSERT INTO `contoh_penggunaan` (`entri_id`, `contoh_teks`, `terjemahan`) VALUES
(123, 'Adhuh biyung, wetengku lara!', 'Aduh ibu, perutku sakit!');

-- Contoh untuk 'adi' (Misal, Entri ID 161 setelah digabung)
-- Ganti 161 dengan ID yang benar setelah insert semua entri
INSERT INTO `contoh_penggunaan` (`entri_id`, `contoh_teks`, `terjemahan`) VALUES
(161, 'Klambine pancen adi tenan.', 'Bajunya memang bagus sekali.');

